# Project: Laboratory3
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = glew.o main_lab8.o
LINKOBJ  = glew.o main_lab8.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -L"C:/Users/acer/Documents/CODING/C++/OpenGL/freeglut-MinGW-3.0.0-1.mp/freeglut/lib/x64" -L"C:/Users/acer/Documents/CODING/C++/OpenGL/glew-2.1.0/lib/Release/x64" -lopengl32 -lfreeglut -lglu32
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/acer/Documents/CODING/C++/OpenGL/freeglut-MinGW-3.0.0-1.mp/freeglut/include" -I"C:/Users/acer/Documents/CODING/C++/OpenGL/glew-2.1.0/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++" -I"C:/Users/acer/Documents/CODING/C++/OpenGL/freeglut-MinGW-3.0.0-1.mp/freeglut/include" -I"C:/Users/acer/Documents/CODING/C++/OpenGL/glew-2.1.0/include"
BIN      = Laboratory8.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

glew.o: glew.c
	$(CPP) -c glew.c -o glew.o $(CXXFLAGS)

main_lab8.o: main_lab8.cpp
	$(CPP) -c main_lab8.cpp -o main_lab8.o $(CXXFLAGS)
